UI page Manage Store
comartek/fs-clone-tinwin-distributor pull request #15
Opened 2022-09-30 08:37 UTC by baott-comartek

+ làm giao diện trang Quản lý kho hàng

git ticket: https://github.com/comartek/fs-clone-tinwin-distributor/issues/14

**Evidence (photos)**

![simulator_screenshot_4FF0D9BB-4538-4F85-86BF-9C308A5FFE13](https://user-images.githubusercontent.com/111269421/193228804-523cae4e-8925-494e-8345-c1f708dbcb7b.png)

![simulator_screenshot_03163C50-5637-469A-B306-001C7596CFB9](https://user-images.githubusercontent.com/111269421/193228968-dbd0a8d7-77ac-41ae-826b-9eebc042fc90.png)

2022-09-30 08:43 UTC, hoang-comartek commented on components/StoreHouse/StoreManage/AllProduct.tsx
> +          renderItem={({item}) => renderProduct(item)}
```suggestion
          renderItem={renderProduct}
```

2022-09-30 08:43 UTC, hoang-comartek commented on components/StoreHouse/StoreManage/BestSellerSupplier.tsx
> +          renderItem={({item}) => renderProduct(item)}
tương tự

2022-09-30 08:44 UTC, hoang-comartek commented on components/StoreHouse/StoreManage/BestSellerTinWin.tsx
> +          renderItem={({item}) => renderProduct(item)}
.

2022-09-30 08:44 UTC, hoang-comartek commented on components/StoreHouse/StoreManage/OutStock.tsx
> +          renderItem={({item}) => renderProduct(item)}
.

2022-09-30 08:45 UTC, hoang-comartek commented on components/StoreHouse/StoreManage/AllProduct.tsx
> +    borderRadius: 8,
color cho vào file chung

2022-10-03 03:03 UTC, phuongna-comartek requested changes

2022-10-03 03:03 UTC, phuongna-comartek commented on components/StoreHouse/StoreManage/BestSellerSupplier.tsx
> +          onPress={() => moveScreen()}>
đã tạo function mới ở trên rồi, không viết inline nữa, sửa thành:
```
          onPress={moveScreen}
```

2022-10-03 03:03 UTC, phuongna-comartek commented on components/StoreHouse/StoreManage/TopProductSupplier/OptionProduct.tsx
> +    }
logic này đang giống hệt nhau, trường hợp nào thì cũng chạy code 
```
      setType(value);
      setProduct(arrTopProduct.filter(item => item.type === value));

```

vậy check if else làm gì?

2022-10-03 03:16 UTC, phuongna-comartek approved these changes

2022-10-03 03:16 UTC, merged