UI/quan.nguyen/UI order manage
comartek/fs-clone-tinwin-distributor pull request #45
Opened 2022-10-13 08:30 UTC by quannq-comartek

**Description**

sort product, get user, log out

**Git Ticket**
https://github.com/comartek/fs-clone-tinwin-distributor/issues/43

**Testing**

- Manual: Yes
- Automation: No

2022-10-13 08:49 UTC, phuongna-comartek requested changes

2022-10-13 08:49 UTC, phuongna-comartek commented on services/apiClient.ts
> +const token = '44FFF543E0EAF65B5481EFCB35C892CE8705D3FDBDEB4727EC0E9CC28E5AB050';
fix cứng token?

2022-10-13 08:49 UTC, phuongna-comartek commented on services/apiClient.ts
> +            'authorization': `Bearer ${token}`,
.

2022-10-14 05:36 UTC, phuongna-comartek requested changes

2022-10-14 05:36 UTC, phuongna-comartek commented on services/apiClient.ts
> +        const getToken = useSelector(store => store.token.tokenState)
k được dùng hook ở bên ngoài React component nhé.
Trường hợp này lưu vào AsyncStorage xong mỗi gọi api thì interceptor lấy ra

2022-10-17 04:28 UTC, quannq-comartek commented on services/apiClient.ts
> +        const getToken = useSelector(store => store.token.tokenState)
done ạ

2022-10-17 09:13 UTC, phuongna-comartek approved these changes

2022-10-17 09:22 UTC, merged